sudo: required

services:
  - docker

before_install:
  - docker-compose build
  - docker image ls
  - docker ps -a

script:
  - netstat -nlpt | grep 3306
  - service mysql stop
  - docker-compose up

after_script:
  - docker-compose down

