sudo: required

services:
  - docker

before_install:
  - docker-compose build
  - docker image ls

install:
  - docker-compose up -d

script:
  - curl http://localhost/phpinfo.php
  - curl http://localhost/db.php

after_script:
  - docker-compose down

