sudo: required

services:
  - docker

before_install:
  - docker --version
  - docker-compose build
  - docker image ls
  - sudo /etc/init.d/mysql stop
  - netstat -nlpt | grep 3306

install:
  - docker-compose up -d

script:
  - curl http://localhost/phpinfo.php
  - curl http://localhost/db.php

after_script:
  - docker-compose down

