version: "3"
services:
  webserver:
    build:
      context: ./docker/build/apache
    container_name: 'my-apache'
    restart: 'always'
    ports:
      - "80:80"
    links:
      - mysql
    volumes:
      - ${DOCUMENT_ROOT-./public_html}:/var/www/html
      - ${PHP_INI-./docker/config/php/php.ini}:/usr/local/etc/php/php.ini
      - ${VHOSTS_DIR-./docker/config/apache}:/etc/apache2/sites-enabled
      - ${LOG_DIR-./logs/apache2}:/var/log/apache2
  mysql:
    image: mysql:5.7
    container_name: 'my-mysql'
    restart: 'always'
    ports:
      - "8889:3306"
    volumes:
      - ${MYSQL_DATA_DIR-./data/mysql}:/var/lib/mysql
      - ${MYSQL_LOG_DIR-./logs/mysql}:/var/log/mysql
      - ./db:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: 'my-phpmyadmin'
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 8889
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '8080:80'

